config/routes.rb
Rails.application.routes.draw do

  delete '/users/:user_id/locations/:location_id', to: "locations#destroy"

  get 'static_pages/home'

  get 'static_pages/help'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "users#new"
  get "/admin", to: "admins#index", as: :admin
  get "/vendor", to: "vendors#index", as: :vendor
  get "/carrier", to: "carriers#index", as: :carrier
  get "/login", to: "sessions#new"
  get "/sessions/dummy", to: "sessions#destroy"

  resources :users do
    resources :locations, :orders
  end

  resources :users do
    member do
      delete :delete_location, to: "locations#delete_comment", as: "delete_comment"
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
    belongs_to :user
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_many :orders, dependent: :destroy
    has_many :locations, dependent: :destroy
    has_secure_password
    validates :email, presence: true, uniqueness: true

    
    
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
    def index
        admin_path
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
  def authorize
    redirect_to login_path, alert: 'You must be logged in' if current_user.nil?
  end
end

app/controllers/carriers_controller.rb
class CarriersController < ApplicationController
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
    def new
        @location = Location.new
    end
    def index
        @locations = Location.all
    end
    def destroy
        @location = Location.find(params[:location_id])
        @location.destroy
        redirect_to user_locations_path(current_user)
    end
    def show
        @location = Location.find(params[:id])
    end
    def edit
        @location = Location.find(params[:id])
    end
    def create       
        @location = Location.new(location_params)
        @location.user_id = params[:user_id]
        if @location.save
            redirect_to user_locations_path(current_user.id)
        else
            render :new
        end
    end
    def update
        @location = Location.find(params[:id])
        if @location.update_attributes(location_params)
          redirect_to user_locations_path
        else
          render :edit
        end
    end
    private
    def location_params
        params.require(:location).permit(:street, :city, :phone, :zipcode, :state, :email)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    def new
        @order = Order.new
    end
    def index
        @orders = Order.all
    end
    def show
        @order = Order.find(params[:id])
    end
    def destroy
        @order = Order.find(params[:id])
        @order.destroy
        redirect_to user_orders_path
    end
    def edit
        @order = Order.find(params[:id])
    end
    def create
        @order = Order.new(order_params)
        @order.user_id = params[:user_id]
        if @order.save
            redirect_to user_orders_path(current_user.id)
        else
            render :new
        end
    end
    def update
        @order = Order.find(params[:id])
        if @order.update_attributes(order_params)
            redirect_to user_orders_path
        else
            render :edit
        end
    end
    private
    def order_params
        params.require(:order).permit(:origin, :destination, :delivery_deadline, :price, :weight, :cube, :carrier)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
      def new
        # Nothing to do here other than render new.html.erb
      end
    
      def create
        user = User.find_by(email: params[:email])

        if user && user.authenticate(params[:password])
          session[:user_id] = user.id
          if user.account_type == "admin"
            redirect_to admin_path
          elsif user.account_type == "vendor"
            redirect_to vendor_path
          else
            redirect_to carrier_path
          end
        else
          flash.now.alert = 'Please Try Again'
          render :new
        end
      end
      def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: "Logged out!"
      end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end
    def show
        @user = User.find(params[:id])

    end
    def index
        @users = User.all
        @location = Location.new
        @order = Order.new
        
    end
    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            flash[:notice] = "You are now signed up."
            if @user.account_type == "admin"
                redirect_to admin_path
              elsif @user.account_type == "vendor"
                redirect_to vendor_path
              else
                redirect_to carrier_path
              end
        else
            render :new
        end
    end

    def edit
        @user = User.find(params[:id])        
    end
    def update
        @user = User.find(params[:id])
        if @user.update_attributes(user_params)
            redirect_to users_path
        else
            render :edit
        end
    end
    def destroy
        @user = User.find(params[:id])
        @user.destroy
        redirect_to root_path
    end
    private
    def user_params
        params.require(:user).permit(:email, :password, :password_confirmation, :account_type)
    end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
    def new
        @order = Order.new
    end
    def create
            @order = Order.new(order_params)
            if @order.save
              redirect_to vendor_path
            else
              render vendor_path
            end
    end
    private
    def order_params
        params.require(:order).permit(:origin, :destination)
    end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carriers_helper.rb
module CarriersHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/carriers/index.html.erb
<div class="home-body">

<ul>
    <li><%= link_to "View Available Orders", user_orders_path(:user_id) %></li>
</ul>
</div>

app/views/locations/edit.html.erb
<h2>Edit Location</h2>
<div class="home-body">
    <%= form_for [:user, @location] do |u| %>
            <div>
                <%= u.label :street %>
                <%= u.text_field :street %>
            </div>
            <div>
                <%= u.label :city %>
                <%= u.text_field :city %>
            </div>
            <div>
                <%= u.label :phone %>
                <%= u.text_field :phone %>
            </div>
            <div>
                <%= u.label :email %>
                <%= u.text_field :email %>
            </div>
            <div>
                <%= u.label :zipcode %>
                <%= u.text_field :zipcode %>
            </div>
            <div>
                <%= u.label :state %>
                <%= u.text_field :state %>
            </div>
            <%= u.submit "Update Location" %>

        <%= link_to "Back to the Location List", user_locations_path(:user_id) %>
    <% end %>
</div>

app/views/locations/index.html.erb
<h2> Locations </h2>
<div class="home-body">
	<ul>
		<% @locations.each do |location| %>
			<li>
				<%= location.street.to_s + " " + location.city.to_s + " " + location.zipcode.to_s + " " + location.state.to_s + " contact: " + location.email %> -|- 
				<%= form_tag(user_location_path(current_user.id, location.id), method: :delete) do %>
					<div><%= submit_tag 'Delete' %></div>
				<% end %>
				<%= link_to "edit", edit_user_location_path(current_user.id, location.id) %>
			</li>
		<% end %>
	</ul>
	<%= link_to "Return to Dashboard", vendor_path %>
</div>

app/views/locations/new.html.erb
<h2>New Location <%= current_user.id %> </h2>
<div class="home-body">
    <%= form_for [:user, @location] do |l| %>
        <div>
            <%= l.label :street %>
            <%= l.text_field :street %>
        </div>
        <div>
            <%= l.label :city %>
            <%= l.text_field :city %>
        </div>
        <div>
            <%= l.label :phone %>
            <%= l.text_field :phone %>
        </div>
        <div>
            <%= l.label :zipcode%>
            <%= l.text_field :zipcode%>
        </div>
        <div>
            <%= l.label :state %>
            <%= l.text_field :state %>
        </div>
        <div>
            <%= l.label :email %>
            <%= l.text_field :email %>
        </div>
        <%= l.submit "Create New Location" %>
    <% end %>
    <%= link_to "Return Home", vendor_path %>
</div>

app/views/orders/edit.html.erb
<h2>Order No. <%= @order.id %></h2>
<div class="home-body">
<%= form_for [:user, @order] do |o| %>
    <% if current_user.account_type != 'carrier' %>
        <div>
            <%= o.label :origin %>
            <%= o.text_field :origin %>
        </div>
        <div>
            <%= o.label :destination %>
            <%= o.text_field :destination %>
        </div>
        <div>
        <%= o.label :weight %>
        <%= o.text_field :weight %>
        </div>
        <div>
        <div>
        <%= o.label :cubic_meters %>
        <%= o.text_field :cube %>
        </div>
        <%= o.label :price %>
        <%= o.text_field :price %>
        </div>
        <div>
            <%= o.label :delivery_deadline %>
            <%= o.text_field :delivery_deadline %>
        </div>
    <% elsif current_user.account_type == 'carrier' %>
        <h2>
            Enter Carrier Contact Information
        </h2>
        </br>
        <div>
            <%= o.label :carrier %>
            <%= o.text_field :carrier %>
        </div>
    <% end %>
  <%= o.submit "Update Order" %>
<% end %>

<%= link_to "Return to Orders", user_orders_path %>
</div>

app/views/orders/index.html.erb
<h2> Order Viewer</h2>
<div class="home-body">
<ul>
	<% if current_user.account_type == "vendor" %>
		<% current_user.orders.each do |o| %>
			<li>
				<%= "Origin: " + o.origin.to_s + " Destination: " +o.destination.to_s + " Delivered By: " + o.delivery_deadline.to_formatted_s(:short) + " Price: " +o.price.to_s + " Pounds: " +o.weight.to_s + " Cubic Meters: " +o.cube.to_s %> -|- 
				<%= form_tag(user_order_path(current_user.id, o.id), method: :delete) do %>
					<div><%= submit_tag 'Delete' %></div>					
				<% end %>	
				<%= link_to "edit", edit_user_order_path(current_user.id,o.id) %>
			</li>
		<% end %>
	<% else %>
		<%	Order.where(carrier: nil).each do |o| %>
			<li>
				<%= o.origin.to_s + " " +o.destination.to_s + " " +o.delivery_deadline.to_s + " " +o.price.to_s + " " +o.weight.to_s + " | " +o.cube.to_s + o.carrier.to_s %> -|- 
				<%= link_to "Detail", user_order_path(current_user.id, o.id) %>
				<%= link_to "Choose Load", edit_user_order_path(current_user.id,o.id) %>
				
			</li>
		<% end %>
	<% end %>
</ul>

<%= link_to "Return to Dashboard", root_path + current_user.account_type.to_s %>
</div>

app/views/orders/new.html.erb
<h2>New Order</h2>
<div class="home-body">
<%= form_for [:user, @order] do |o| %>
    <div>
        <%= o.label :origin %>
        <%= o.select(:origin, options_for_select(Location.all.map(&:street))) %>
    </div>
    <div>
        <%= o.label :destination %>
        <%= o.select(:destination, options_for_select(Location.all.map(&:street))) %>
    </div>
    <div>
        <%= o.label :weight %>
        <%= o.text_field :weight %>
    </div>
    <div>
        <%= o.label :cubic_meters %>
        <%= o.text_field :cube %>
    </div>
    <div>
        <%= o.label :price %>
        <%= o.text_field :price %>
    </div>
    <div>
        <%= o.label :delivery_deadline %>
        <%= o.text_field :delivery_deadline %>
    </div>
  <%= o.submit "Create New Order" %>
<% end %>
<%= link_to "Return to Dashboard", vendor_path %>
</div>

app/views/orders/show.html.erb
<h2>Order Information</h2>
<div class="home-body">
<ul>
    <li>
        Origin: 
        <%= @order.origin %>
    </li>
    <li>
        Destination:
        <%= @order.destination %> 
    </li>
    <li>
        Delivery Deadline:
        <%= @order.delivery_deadline %>
    </li>
    <li>
    Price:
        <%= @order.price %> 
    </li>
</ul>
<%=link_to "Return to Order Viewer", user_orders_path %>
</div>

app/views/users/edit.html.erb
<h2>Edit <%= @user.email %> </h2>
<div class="home-body">
<%= form_for @user do |u| %>
  <div>
    <%= u.label :email %>
    <%= u.text_field :email %>
  </div>
  <div>
    <%= u.label :password %>
    <%= u.password_field :password %>
  </div>
  <div>
  <%= u.label :password_confirmation %>
  <%= u.password_field :password_confirmation %>
</div>
  <div>
    <%= u.label :phone_number %>
    <%= u.text_field :phone_number %>
  </div>
  <div>
    <%= u.label :account_type %><br />
    <%= u.label :account_type, "carrier", :value => "carrier"  %>
    <%= u.radio_button :account_type, "carrier" %>
    <%= u.label :account_type, "vendor", :value => "vendor" %>
    <%= u.radio_button :account_type, "vendor" %>
    <%= u.label :account_type, "admin", :value => "admin" %>
    <%= u.radio_button :account_type, "admin" %>
  </div>
  <%= u.submit "Update User" %>
<% end %>

<%= link_to "Back to the User Viewer", users_path %>
</div>

app/views/users/index.html.erb
<div class="home-body">
<ul>
<% @users.each do |user| %>
    <li>
        <% user_id = (user.account_type.to_s + " - " + user.email.to_s) %>
        <%= link_to user_id, user_path(user) %> - | <%= link_to "edit", edit_user_path(user) %>
        </li>
<% end %>
</ul>

<%= link_to "return to admin dashboard", admin_path %>
</div>

app/views/users/new.html.erb
<div class="home-body">

<div class="user-in">
    <h1>Log in</h1>
    <p id="alert"><%= alert %></p>
    <%= form_tag sessions_path do %>
      <div class="field">
        <%= label_tag :email %>
        <%= text_field_tag :email, params[:email] %>
      </div>
      <div class="field">
        <%= label_tag :password %>
        <%= password_field_tag :password %>
      </div>
      <div class="actions animated pulse"><%= submit_tag "Log In" %></div>
    <% end %>
</div>

<div class="user-in">
    <h1>Sign Up</h1>
    <%= form_for @user do |f| %>
      <% if @user.errors.any? %>
        <div class="error_messages">
          <h2>Form is invalid</h2>
          <ul>
            <% for message in @user.errors.full_messages %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.label :email %>
        <%= f.text_field :email %>
      </div>
      <div class="field">
        <%= f.label :password %>
        <%= f.password_field :password %>
      </div>
      <div class="field">
        <%= f.label "Confirm Password" %>
        <%= f.password_field :password_confirmation %>
      </div>

      <div class="field">
        <ul> 
          <%= f.label :account_type %><br />
          <li>
            <%= f.label :account_type, "Carrier", :value => "carrier"  %>
            <%= f.radio_button :account_type, "carrier" %>
          </li>
          <li>
            <%= f.label :account_type, "Vendor", :value => "vendor" %>
            <%= f.radio_button :account_type, "vendor" %>
          </li>
        </ul>
      </div>
      <div class="actions"><%= f.submit %></div>
      
    <% end %>
</div>
</div>

app/views/vendors/index.html.erb
<div class="home-body">
    <ul>
        <li><%= link_to "Create a new Order", new_user_order_path(current_user.id) %></li>
        <li><%= link_to "View Orders", user_orders_path(current_user.id) %></li>
        <li><%= link_to "Create a new Location", new_user_location_path(current_user.id) %></li>
        <li><%= link_to "View Locations", user_locations_path(current_user.id) %></li>
    </ul>
</div>

app/views/vendors/new.html.erb
<div class="home-body">
<%= form_for @order do |item| %>
        <div>
          <%= item.label :origin %>
          <%= item.text_field :origin %>
        </div>
        <div>
          <%= item.label :destination %>
          <%= item.text_field :destination %>
        </div>
        <%= item.submit "create" %>
    <% end %>
    <%= link_to "HOME", vendor_path %>
</div>